---
title: ""
sidebar: false
---

# STAT 253: Statistical Machine Learning 
Macalester College, Spring 2026  

Statistics is not just about theories & numbers — it’s about making sense of the world.  

::: {.callout-tip title="📖 A Thought from H. G. Wells"}  
> “Statistical thinking will one day be as necessary for efficient citizenship as the ability to read and write.”  
:::  

Welcome to the world of Statistics! In this course, you’ll learn how to analyze data, test research hypotheses, and make predictions in ways that matter.  

**Instructor:** Md Mutasim Billah <br> **Class meeting times:**

-   **Section 03**: M/W/F 02:20-03:20pm, THTR 213


**Office hours:**

-   **Location:** My office (OLRI 234) and over Zoom
-   **Times:** M/W: 12:00pm - 12:30pm (in-person), T/TR: 2pm - 3pm (Over [zoom](https://macalester.zoom.us/j/99762878654?pwd=gt7VvSNT0ubKsV2icMV3z8J0GyHKMy.1), password: 123456)
-   **By Appointment:** I'm also happy to meet one-on-one if my normal drop-in/virtual hours don't work for you. Shoot me an email and we can arrange it over [zoom](https://macalester.zoom.us/j/99762878654?pwd=gt7VvSNT0ubKsV2icMV3z8J0GyHKMy.1), password: 123456.
-   **Email Response Time:** I do my best to reply to emails promptly during weekdays. Please note that messages sent after 3:00 pm or on weekends may take longer to receive a response.

------------------------------------------------------------------------

[**STAT 253 Preceptor Office Hours:**]{.underline} There is a link to a Google Calendar containing *all* preceptor office hours available at the top of the course Moodle page!

[**Data and R Support:**]{.underline} In addition to our course preceptors, there is support on campus for working with data and R / RStudio. See [https://www.macalester.edu/mscs/data-support](https://www.macalester.edu/mscs/data-support)  for more information.



------------------------------------------------------------------------

This course website will be updated throughout the semester with new activities, assignments, and announcements, so please bookmark this page if you are enrolled in the course!

If you find any typos, bugs, dead links, or have other questions, please email [mbillah@macalester.edu](mailto:mbillah@macalester.edu){.email}
