---
title: "Homework 4"
subtitle: "Stat 253"
author: "Your Name"
date: today
format:
  html:
    toc: true
    toc-depth: 2
    embed-resources: true
    fig-width: 5
    fig-height: 3
execute:
  error: false
  warning: false
knitr:
  opts_chunk:
    collapse: true
    message: false
---


# Notes 

(@) Please **update the author name** to your name! 
(@) This document is for your answers only. Do NOT write out the homework questions in this document. Writing out the questions makes it very challenging to grade the homework. (You can create a separate document for your own records if you wish.) 
(@) Besides adding your answers/code, please DO NOT make any deletions or changes to the structure of this template! 



# Setup 

Put any code you need to load packages and load/prep data here. 

```{r}

```


---

title: 'Homework 4: Classification with Logistic Regression & LASSO'

subtitle: STAT 253

format:

  html:

    toc: true

    embed-resources: true

---



# Exercises



## Exercise 1: Model building



### Part a



### Part b



## Exercise 2: `model_1` interpretation & prediction       



### Part a



### Part b



### Part c



### Part d



### Part e



## Exercise 3: `model_1` in-sample evaluation 



### Part a



### Part b



### Part c



### Part d



## Exercise 4: Going big 



### Part a



### Part b



### Part c



## Exercise 5: `model_4` in-sample evaluation continued



### Part a



### Part b



### Part c



### Part d



## Exercise 6: LASSO!



### Part a



### Part b



### Part c



### Part d



### Part e



## Exercise 7: Pick a model!



### Part a



### Part b



### Part c



### Part d



### Part e



## Exercise 8: Learning Reflection



## Exercise 9: Resource Reflection




# Done!

- Render your QMD to HTML.
- Check that HTML to make sure there are no errors or formatting issues. 
- Submit the HTML on Moodle.


